# See the following for documentation:
# https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
# https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/lambda_edge/template.yaml

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: deno.land

Resources:
  DenoLandCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - deno.land
        Enabled: true
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:us-east-1:996721126982:certificate/17ec3785-d60f-46af-837f-fbeefdb31203"
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          TargetOriginId: DenoLandOrigin
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref DenoLandFunction.Version
          ForwardedValues:
            QueryString: false
            Headers:
              - Accept
          ViewerProtocolPolicy: redirect-to-https
        Origins:
          - Id: DenoLandOrigin
            DomainName: "deno.land.s3.amazonaws.com"
            S3OriginConfig:
              OriginAccessIdentity: ""

  DenoLandFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live3
      CodeUri: ./src/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Role: "arn:aws:iam::996721126982:role/service-role/sam-app-role-name"

Outputs:
  DenoLandCloudFront:
    Description: DenoLandCloudFront DomainName
    Value: !GetAtt DenoLandCloudFront.DomainName
